// <auto-generated />
using System;
using ConsoleAppTaskEf;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleAppTaskEf.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20201218075028_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ConsoleAppTaskEf.OrdersNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("ConsoleAppTaskEf.ProductsNew", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("Orderid")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ordersNewId")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("ordersNewId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ConsoleAppTaskEf.ProductsNew", b =>
                {
                    b.HasOne("ConsoleAppTaskEf.OrdersNew", "ordersNew")
                        .WithMany("products")
                        .HasForeignKey("ordersNewId");

                    b.Navigation("ordersNew");
                });

            modelBuilder.Entity("ConsoleAppTaskEf.OrdersNew", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
